version: '3.8'
services:
   namenode:
      image: apache/hadoop:3
      hostname: namenode
      command: ["hdfs", "namenode"]
      ports:
        - 9870:9870
      env_file:
        - ./config
      environment:
          ENSURE_NAMENODE_DIR: "/opt/hadoop/dfs/name"
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
      networks:
        - hadoop

   datanode:
      image: apache/hadoop:3
      command: ["hdfs", "datanode"]
      env_file:
        - ./config
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
      networks:
        - hadoop

   resourcemanager:
      image: apache/hadoop:3
      hostname: resourcemanager
      command: ["yarn", "resourcemanager"]
      ports:
         - 8088:8088
      env_file:
        - ./config
      volumes:
        - ./test.sh:/opt/hadoop/test.sh
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
      networks:
        - hadoop

   nodemanager:
      image: apache/hadoop:3
      command: ["yarn", "nodemanager"]
      env_file:
        - ./config
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
      networks:
        - hadoop

networks:
  hadoop:
